### ISSUE TITLE
Running "cmake ." reports an error in CMakeLists.txt

### ISSUE THREAD

**Issue by pm215** [ARM-software/tarmac-trace-utilities#4]
I tried to build using the commands suggested in the readme, but "cmake ." fails with an error message suggesting a bug in CMakeLists.txt:
```
$ cmake .
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.22.30
CMake Error at CMakeLists.txt:46 (install):
  install TARGETS given target "tarmac-callinfo" which does not exist in this
  directory.


-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Configuring incomplete, errors occurred!
See also "/home/petmay01/src/tarmac-trace-utilities/CMakeFiles/CMakeOutput.log".
```

This is on an Ubuntu 18.04.5 LTS with cmake version 3.10.2.

I don't see anything obviously diagnostic in the CMakeOutput.log but I have attached it anyway.
[CMakeOutput.log](https://github.com/ARM-software/tarmac-trace-utilities/files/6790708/CMakeOutput.log)

**Comment by statham-arm** [comment]
I was confused by this because that cmake command _isn't_ failing in CI! But now I see that the Github 18.04 CI image includes cmake 3.20 rather than Ubuntu 18.04's standard cmake, so mystery solved.

I can reproduce it locally; thanks for the report.
