### ISSUE TITLE
Unrecognized syntax in tarmac file

### ISSUE THREAD

**Issue by WonderfulVoid** [ARM-software/tarmac-trace-utilities#9]
tarmac-browser doesn't like the following entry:
> **2884500 ps  ES  (0000000000000188:9e6703e0) O el3h_s:         FMOV     d0,xzr
>                     R V0<63:0> 0000000000000000
>                     R V0<127:64> 0000000000000000**

```
$ ./tarmac-browser tarmac._CLUSTER_g_core_0__g_little_u_helios_core_u_vcpu_u_cpu_u_helios_dpu_u_follow_.t0.log 
index file tarmac._CLUSTER_g_core_0__g_little_u_helios_core_u_vcpu_u_cpu_u_helios_dpu_u_follow_.t0.log.index does not exist; building it
tarmac._CLUSTER_g_core_0__g_little_u_helios_core_u_vcpu_u_cpu_u_helios_dpu_u_follow_.t0.log:199: Unrecognised token
                    R V0<63:0> 0000000000000000
                        ^

```

**Comment by statham-arm** [comment]
Thanks for the report. Can you tell us what Tarmac producer emitted that snippet?

**Comment by WonderfulVoid** [comment]
The tarmac file was generated by the Neoverse E1 cycle model.
